"""Vision embedding extraction: a real encoder path and a synthetic proxy.

Drift detection and active learning operate on embeddings, not raw
pixels, so this module is the single seam between "real DINOv3/CLIP/
VLM vision-tower features" and the synthetic charts generated by
``production_vlm.utils.synthetic_charts``. Swap ``SyntheticEmbeddingProxy``
for ``RealVisionEncoder`` once you have GPU + network access and the
rest of the drift/active-learning pipeline is unchanged.

Reference: DINOv3 (Oquab et al. successor line, Meta AI, 2025) and
SigLIP-2 (Tschannen et al., 2025) are the dominant 2026 choices for
general-purpose vision embeddings used in drift monitoring, given
their strong linear-probe transfer without task-specific fine-tuning.
"""

from __future__ import annotations

import zlib
from typing import Protocol

import numpy as np
from PIL import Image


class VisionEncoder(Protocol):
    """Common interface: a batch of PIL images in, a (N, D) embedding matrix out."""

    embedding_dim: int

    def encode(self, images: list[Image.Image]) -> np.ndarray: ...


class RealVisionEncoder:
    """Wraps a HF `transformers` vision backbone (DINOv3/SigLIP-2/CLIP-style) for real embeddings.

    Requires the optional `ml` dependency group:
        pip install -e ".[ml]"

    Usage:
        encoder = RealVisionEncoder("facebook/dinov2-base")  # or a DINOv3/SigLIP-2 checkpoint once resolved
        embeddings = encoder.encode(list_of_pil_images)
    """

    def __init__(self, checkpoint: str, device: str | None = None) -> None:
        import torch
        from transformers import AutoImageProcessor, AutoModel

        self.checkpoint = checkpoint
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.processor = AutoImageProcessor.from_pretrained(checkpoint)
        self.model = AutoModel.from_pretrained(checkpoint).to(self.device).eval()
        self.embedding_dim = self.model.config.hidden_size

    def encode(self, images: list[Image.Image]) -> np.ndarray:
        import torch

        inputs = self.processor(images=images, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.model(**inputs)
        # CLS-token / pooled embedding, matching the convention most
        # drift-monitoring setups use for a single per-image vector.
        has_pooler = hasattr(outputs, "pooler_output") and outputs.pooler_output is not None
        pooled = outputs.pooler_output if has_pooler else outputs.last_hidden_state[:, 0, :]
        return pooled.cpu().numpy()


class SyntheticEmbeddingProxy:
    """Deterministic, dependency-light stand-in for a real vision encoder.

    Rather than hashing pixels (which would be brittle and
    uninformative), this derives an embedding from the *structured
    chart metadata* (category values, palette, chart type) the same
    synthetic generator already produces — giving embeddings that
    move sensibly with real semantic/style changes (so a style_shift
    chart genuinely lands far from the reference centroid) without
    requiring a real network forward pass. This keeps the drift/active
    learning example fully runnable offline while preserving the
    property the real pipeline depends on: same encoder, comparable
    embedding space, distribution shift is visible in similarity space.
    """

    def __init__(self, embedding_dim: int = 64, seed: int = 0, shift_magnitude: float = 12.0) -> None:
        self.embedding_dim = embedding_dim
        self._rng = np.random.default_rng(seed)
        # Fixed random projection so the same chart always maps to the same
        # embedding region across calls (reproducibility), while different
        # charts/styles map to different regions (so drift is detectable).
        self._style_projection = self._rng.normal(size=(8, embedding_dim))
        self._value_projection = self._rng.normal(size=(6, embedding_dim))
        self._category_hash_dim = embedding_dim
        # Fixed OOD shift direction: a real style/lighting/domain shift moves
        # an encoder's outputs in a *consistent* direction, not a fresh random
        # one per sample — regenerating this per-call would average out to
        # near-zero across a batch and make drift undetectable.
        shift_direction = self._rng.normal(size=embedding_dim)
        self._shift_direction = shift_direction / np.linalg.norm(shift_direction)
        self._shift_magnitude = shift_magnitude

    def _chart_to_vector(self, chart) -> np.ndarray:
        # Style features: chart type (one-hot-ish) + palette signal (style_seed parity is a crude OOD flag).
        style_feat = np.zeros(8)
        style_feat[{"bar": 0, "line": 1, "pie": 2}.get(chart.chart_type, 3)] = 1.0
        style_feat[5] = len(chart.categories) / 6.0
        # zlib.crc32, NOT Python's built-in hash(): hash() on strings is
        # randomized per-process by default (PYTHONHASHSEED, a security
        # feature against hash-collision DoS), so it produces a different
        # value every time the interpreter starts. That silently made every
        # downstream embedding -- and therefore every OOD/drift detection
        # rate computed from it -- non-reproducible across process runs,
        # directly contradicting this class's own "deterministic" docstring
        # claim. crc32 is a genuinely deterministic string hash.
        style_feat[6] = zlib.crc32(chart.units.encode()) % 1000 / 1000.0
        style_feat[7] = 1.0

        values = np.array(chart.values[:6] + [0.0] * max(0, 6 - len(chart.values[:6])))
        norm_values = (values - values.mean()) / (values.std() + 1e-6)

        vec = style_feat @ self._style_projection + norm_values @ self._value_projection
        return vec

    def encode_charts(self, charts: list, style_shift_flags: list[bool] | None = None) -> np.ndarray:
        """Encode SyntheticChart objects directly (preferred — carries true style_shift signal)."""
        flags = style_shift_flags or [False] * len(charts)
        vectors = []
        for chart, is_shift in zip(charts, flags):
            v = self._chart_to_vector(chart)
            if is_shift:
                # Real OOD style shift in a vision encoder shows up as a
                # consistent directional offset in embedding space, not
                # pure noise -- apply the same fixed shift vector to every
                # shifted sample so the signal doesn't average out.
                v = v + self._shift_magnitude * self._shift_direction
            vectors.append(v)
        return np.stack(vectors)

    def encode(self, images: list[Image.Image]) -> np.ndarray:
        # Protocol compliance for callers that only have raw images; falls
        # back to a coarse pixel-statistics embedding (mean/std per channel
        # tiled out), which is far weaker than encode_charts but keeps the
        # interface honest for arbitrary image input.
        vectors = []
        for img in images:
            arr = np.asarray(img.convert("RGB"), dtype=np.float64) / 255.0
            stats = np.concatenate([arr.mean(axis=(0, 1)), arr.std(axis=(0, 1))])
            tiled = np.tile(stats, self.embedding_dim // len(stats) + 1)[: self.embedding_dim]
            vectors.append(tiled)
        return np.stack(vectors)
